spring.application.name=auth-service
server.port=4005
jwt.secret=MzJieXRlc2VjcmV0a2V5Zm9yYXV0aG1lc2VydmljZXM=

# Eureka Config
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}
