### GET request to example server
POST http://localhost:4000/patients
Content-Type: application/json


{
  "name": "Nguyen Van Đẹp trai",
  "email": "hauanhh2005.nguyen@example.com",
  "address": "123 Ha Dong, Ha Noi",
  "dateOfBirth": "2004-05-20"
}

###
