POST  http://localhost:4004/api/billing/accounts/51d19e03-5c1c-4ee5-9efb-0cb67b3486fb/transactions
Content-Type: application/json
Authorization: Bearer {{accessToken}}


{
  "amount": 520000.0,
  "type": "DEBIT",
  "description": "Tra tien soi noi chieu"
}

###

