spring.application.name=doctor-service
server.port=4003

# Spring Boot will automatically pick up SPRING_DATASOURCE_URL, USERNAME, PASSWORD from Docker env.
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
