spring.application.name=billing-service
server.port=4001
grpc.server.port=9001
spring.main.allow-bean-definition-overriding=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/