### GET request to example server
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "hau123@gmail.com",
  "password": "123456"
}

> {% client.global.set("token", response.body.token) %}