### GET request to example server
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email": "hauu2005@gmail.com",
  "password": "123456"
}

> {% client.global.set("accessToken", response.body.accessToken) %}