###
POST http://localhost:4004/api/billing/accounts
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "patientId": "e1b2f48a-b10a-47e2-ab59-695a11c23583",
  "name": "Nguyen Văn Hậu a",
  "email": "haunguyenvan1234@gmail.com"
}

###