spring.application.name=patient-service
server.port=4000
spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
logging.level.root=info
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
