spring.application.name=analytics-service
server.port=4006
spring.profiles.default=local

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=${APP_DDL_AUTO:update}
spring.kafka.bootstrap-servers=${APP_KAFKA_BOOTSTRAP_SERVERS}
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.main.allow-circular-references=true
spring.kafka.listener.missing-topics-fatal=false
eureka.client.service-url.defaultZone=${APP_EUREKA_URL}

spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=20000

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true
management.health.livenessstate.enabled=true
management.health.readinessstate.enabled=true
