spring.application.name=appointment-service
server.port=4002

# Thêm dòng này để Spring chọn đúng driver
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Eureka — để Spring nhận từ env var của docker-compose
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://eureka-server:8761/eureka/}
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.client.enabled=true

# Springdoc
springdoc.packages-to-scan=com.pm.appointmentservice.interfaces.rest