POST http://localhost:4002/appointment
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "patientId": "9720a662-c0c3-49be-a122-6e5ba3638f0d",
  "appointmentDate": "2025-11-20T14:30:00"
}

###