### Post request to example server
POST http://localhost:4004/api/appointment
Content-Type: application/json
Authorization: Bearer {{accessToken}}


{
  "patientId": "6bed1de7-dd12-4e96-b032-0e1d13640ecb",
  "appointmentDate": "2025-12-07T11:00:00"
}

###